tasks:
  - init: |
      pip install robotframework
    command: |
      python -m pip install --upgrade pip
      pip install robotframework-browser
      rfbrowser init
image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode
    - PKief.material-icon-theme
    - dbaeumer.vscode-eslint